stages:
  - build
  - tag
  - deploy

frontend:build:
  stage: build
  image: node:8
  script:
  # Build
  - cd /builds/kvasbo/Make_Me_God/src/makemegod-client/
  - yarn
  - yarn run build
  # End build
  artifacts:
    paths:
    - src/makemegod-client/build
    expire_in: 1 week

backend:build:
  stage: build
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind 
  script:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  # Build
  - cd /builds/kvasbo/Make_Me_God/src/backend/
  - docker build -t kvasbo/makemegod-backend:dev-$CI_COMMIT_REF_NAME .
  - docker push kvasbo/makemegod-backend:dev-$CI_COMMIT_REF_NAME
  # End build

backend:tag:
  stage: tag
  image: docker:stable
  only:
  - master
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
  - docker:dind 
  script:
  # Tag latest version
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
  - docker pull kvasbo/makemegod-backend:dev-$CI_COMMIT_REF_NAME
  - docker tag kvasbo/makemegod-backend:dev-$CI_COMMIT_REF_NAME kvasbo/makemegod-backend:latest
  - docker push kvasbo/makemegod-backend:latest

frontend:deploy:
  stage: deploy
  only:
  - master
  image: python:latest
  variables:
    AWS_BUCKET_NAME: makemegod.com
  dependencies:
  - frontend:build
  script:
  # Start amazon setup
  - apt-get update && apt-get install curl unzip -y
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  # Deploy frontend
  - /root/bin/aws s3 sync /builds/kvasbo/Make_Me_God/src/makemegod-client/build/ "s3://${AWS_BUCKET_NAME}/" --cache-control "max-age=0"

# backend:deploy:
#  stage: deploy
#  only:
#  - master
#  - allnew
#  image: python:latest
#  script:
#  # Start amazon setup
#  - pip install awsebcli --upgrade --user
#  # Deploy backend
#  - cd /builds/kvasbo/Make_Me_God/src/backend/
#  - ~/.local/bin/eb deploy -m "$CI_COMMIT_REF_NAME $CI_COMMIT_SHORT_SHA" --l $CI_COMMIT_SHORT_SHA