build:frontend:
  stage: build
  image: node:8
  script:
  # Build
  - cd /builds/kvasbo/Make_Me_God/src/makemegod-client/
  - yarn
  - yarn run build
  # End build
  artifacts:
    paths:
    - src/makemegod-client/build
    expire_in: 1 week

deploy:
  stage: deploy
  only:
  - master
  image: python:latest
  variables:
    AWS_BUCKET_NAME: makemegod.com
  dependencies:
  - build:frontend
  script:
  # Start amazon setup
  - apt-get update && apt-get install curl unzip -y
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  # Deploy frontend
  - /root/bin/aws s3 sync /builds/kvasbo/Make_Me_God/src/makemegod-client/build/ "s3://${AWS_BUCKET_NAME}/" --cache-control "max-age=0"