version: "3.2"

services:
  makemegod:
    # build:
      #dockerfile: Dockerfile
      #context: .
    image: ghcr.io/kvasbo/make-me-god:sha-41850b8
    ports:
      - "80:80"
    volumes:
      - ./bibles:/makemegod/bibles
      # - ./dist:/makemegod/dist
