version: "3.2"

services:
  makemegod:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./bibles:/makemegod/bibles
      - ./dist:/makemegod/dist
