version: "3.2"

services:
  backend:
    container_name: makemegod
    image: kvasbo/makemegod:latest
    ports:
      - "6666:80"
    volumes:
      - ./bibles:/makemegod/bibles
  tunnel:
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run --token MY_TOKEN
    volumes:
      - ./tunnel:/etc/cloudflared
networks:
  default:
    external:
      name: makemegod