version: "3.2"

services:
  makemegod:
    image: kvasbo/make_me_god:latest
    ports:
      - "${NETWORK_PORT}:80"
    volumes:
      - ./bibles:/makemegod/bibles
networks:
  default:
      name: ${NETWORK_NAME}
      external: true
