version: "3.2"

services:
  backend:
    container_name: makemegod
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    volumes:
      - ./bibles:/makemegod/bibles
