version: "3.2"

services:
  backend:
    container_name: makemegod
    image: kvasbo/makemegod:latest
    ports:
      - "80:80"
    volumes:
      - ./bibles:/makemegod/bibles
networks:
  default:
    external:
      name: kvasbo
