apiVersion: apps/v1
kind: Deployment
metadata:
  name: makemegod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makemegod
  template:
    metadata:
      labels:
        app: makemegod
    spec:
      containers:
      - name: makemegod-app
        image: ghcr.io/kvasbo/make-me-god:master
        ports: 
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 3
