apiVersion: v1
kind: Service
metadata:
  name: makemegod
spec:
  type: NodePort
  selector:
    app: makemegod
    role: web
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP