name: Build and publish manually

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/make_me_god:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build image
        run: docker build -t kvasbo/makemegod .
      - name: Tag image
        run: docker tag kvasbo/makemegod registry.digitalocean.com/kvasbo/makemegod:${GITHUB_SHA}
      - name: Tag image
        run: docker tag kvasbo/makemegod registry.digitalocean.com/kvasbo/makemegod:latest
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/kvasbo/makemegod:${GITHUB_SHA}
